# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ReactNativeFirebaseUIExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # The following line hard selects GoogleUtilities 5.3.7
  # This line should probably be removed in the future but
  # fixes a linker problem on iOS, due to the fact that if
  # we ommit this line, then 5.4.0 gets installed, which
  # causes a link error.
  pod 'GoogleUtilities', '~> 5.3.7'


  # Pods for ReactNativeFirebaseUIExample

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.15.0'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  pod 'Firebase/AdMob', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Database', '~> 5.15.0'
  pod 'Firebase/Functions', '~> 5.15.0'
  pod 'Firebase/DynamicLinks', '~> 5.15.0'
  pod 'Firebase/Firestore', '~> 5.15.0'
  # pod 'Firebase/Invites', '~> 5.15.0'
  pod 'Firebase/Messaging', '~> 5.15.0'
  pod 'Firebase/RemoteConfig', '~> 5.15.0'
  pod 'Firebase/Storage', '~> 5.15.0'
  pod 'Firebase/Performance', '~> 5.15.0'
  pod 'Fabric', '~> 1.7.13'
  pod 'Crashlytics', '~> 3.10.9'

  pod 'SDWebImage', '~> 4.0'
end
